Create sightingstage enum in migration explicitly
Alembic didn't include anything to create the enum when it's "alter table" (I
think), causing the type "sightingstage" to not exist:

```
root@4b1ff276d7d2:/code# invoke app.db.upgrade --no-backup
2021-06-09 12:54:45,315 [INFO] [app] Using app.config 'docker_local_config.LocalConfig'
2021-06-09 12:54:46,012 [INFO] [alembic.runtime.migration] Context impl PostgresqlImpl.
2021-06-09 12:54:46,013 [INFO] [alembic.runtime.migration] Will assume transactional DDL.
2021-06-09 12:54:46,025 [INFO] [alembic.runtime.migration] Running upgrade fa952f537929 -> adb5d1a314bc, empty message
2021-06-09 12:54:46,076 [INFO] [alembic.runtime.migration] Running upgrade adb5d1a314bc -> 58bf0e49cbf7, adding sighting stage
2021-06-09 12:54:46,108 [CRITICAL] [tasks.app.db] Database upgrade failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedObject: type "sightingstage" does not exist
LINE 1: ALTER TABLE sighting ADD COLUMN stage sightingstage NOT NULL
                                              ^
```

After that, it complained about the column being null:

```
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) column "stage" contains null values

[SQL: ALTER TABLE sighting ADD COLUMN stage sightingstage NOT NULL]
```

And a plain `default='identification'` didn't work, had to use
`server_default=sa.text("'identification'")` to insert some sql into "add
column".

See https://alembic.sqlalchemy.org/en/latest/ops.html